apiVersion: networking.tanzu.vmware.com/v1alpha1
kind: EgressPoint
metadata:
  name: spring-metal-ext-svc-egress
  namespace: default
spec:
  targets:
  - hosts:
    - genai-proxy.sys.tas.vmtanzu.com
    port:
      number: 8443
      protocol: HTTPS
  - hosts:
    - tcp.tas.vmtanzu.com
    port:
      number: 1028
      protocol: TCP